#!/usr/bin/env python3
"""Static contract checks for infra-owned Shaka production app deploy."""
from pathlib import Path
import re
import unittest

ROOT = Path(__file__).resolve().parents[1]
WORKFLOW = ROOT / ".github" / "workflows" / "app-production-deploy.yml"
SCRIPT = ROOT / "scripts" / "deploy-shaka-production.sh"
MIGRATION_SCRIPT = ROOT / "scripts" / "run-shaka-db-migration.sh"
ALLOY = ROOT / "deploy" / "grafana" / "alloy-otlp-config.alloy"
SYSTEMD = ROOT / "deploy" / "systemd" / "shaka-server.service"

class AppProductionDeployTest(unittest.TestCase):
    def test_workflow_is_infra_owned_and_uses_single_production_environment(self):
        text = WORKFLOW.read_text(encoding="utf-8")
        self.assertIn("workflow_dispatch:", text)
        self.assertIn("if: github.ref_name == 'main'", text)
        self.assertIn("environment: production", text)
        self.assertIn("deploy_confirmation=deploy-shaka-production", text)
        self.assertIn("Required unless db_migration_mode=validate-only", text)
        self.assertIn("db_migration_mode:", text)
        self.assertIn("- validate-only", text)
        self.assertIn("- apply", text)
        self.assertIn("db_migration_confirmation:", text)
        self.assertIn("db_migration_baseline_existing_schema:", text)
        self.assertIn("Approve production DB migration apply", text)
        self.assertIn("environment: production-db-migration", text)
        self.assertIn("db_migration_gate:", text)
        self.assertIn("id-token: write", text)
        self.assertIn("build-server-artifact:", text)
        self.assertIn("Deploy Shaka app from verified artifact", text)
        self.assertIn("repository: dannawagyu/shaka-server-spring", text)
        self.assertIn("working-directory: server", text)
        self.assertIn("./gradlew test --no-daemon", text)
        self.assertIn("./gradlew clean bootJar --no-daemon", text)
        self.assertIn("infra/scripts/deploy-shaka-production.sh", text)
        self.assertIn("GRAFANA_CLOUD_OTLP_ENDPOINT: ${{ secrets.GRAFANA_CLOUD_OTLP_ENDPOINT }}", text)
        self.assertIn("GRAFANA_CLOUD_OTLP_USERNAME: ${{ secrets.GRAFANA_CLOUD_OTLP_USERNAME }}", text)
        self.assertIn("GRAFANA_CLOUD_OTLP_PASSWORD: ${{ secrets.GRAFANA_CLOUD_OTLP_PASSWORD }}", text)
        self.assertIn("SHAKA_PROD_SSH_KNOWN_HOSTS", text)
        self.assertIn("OTEL_JAVA_AGENT_SHA256", text)
        self.assertIn("actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02", text)
        self.assertIn("actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093", text)
        self.assertIn("name: shaka-server-migration-sql", text)
        self.assertIn("Stage server migration SQL", text)
        self.assertIn("cp -R server/src/main/resources/db/migration migration-sql/", text)
        self.assertIn("Run trusted Flyway migration gate before app mutation", text)
        self.assertIn("infra/scripts/run-shaka-db-migration.sh", text)
        self.assertLess(
            text.index("Run trusted Flyway migration gate before app mutation"),
            text.index("Deploy server artifact and OTLP runtime through infra"),
        )
        self.assertIn("inputs.db_migration_mode != 'validate-only'", text)
        self.assertIn("SHAKA_PROD_DB_URL: ${{ secrets.SHAKA_PROD_DB_URL }}", text)
        self.assertIn("SHAKA_PROD_DB_USERNAME: ${{ secrets.SHAKA_DB_USERNAME }}", text)
        self.assertIn("SHAKA_PROD_DB_PASSWORD: ${{ secrets.SHAKA_DB_PASSWORD }}", text)
        self.assertNotIn("secrets.SHAKA_PROD_DB_USERNAME", text)
        self.assertNotIn("secrets.SHAKA_PROD_DB_PASSWORD", text)
        self.assertIn("SHAKA_RDS_DB_INSTANCE_IDENTIFIER: ${{ vars.SHAKA_RDS_DB_INSTANCE_IDENTIFIER }}", text)
        self.assertIn("SHAKA_FLYWAY_BASELINE_ON_MIGRATE: ${{ inputs.db_migration_baseline_existing_schema }}", text)
        self.assertNotIn("vars.SHAKA_FLYWAY_CLI_URL", text)
        self.assertNotIn("vars.SHAKA_FLYWAY_CLI_SHA256", text)
        self.assertNotIn("vars.SHAKA_MYSQL_CONNECTOR_J_URL", text)
        self.assertNotIn("vars.SHAKA_MYSQL_CONNECTOR_J_SHA256", text)
        self.assertIn("Configure AWS credentials for migration apply backup verification", text)
        self.assertIn("aws-actions/configure-aws-credentials@ff717079ee2060e4bcee96c4779b553acc87447c", text)
        self.assertIn("role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}", text)
        self.assertNotIn("aws-access-key-id", text)
        self.assertNotIn("aws-secret-access-key", text)
        self.assertIn("SHAKA_PROD_URL", text)
        self.assertIn("GRAFANA_PROMETHEUS_REMOTE_WRITE_URL", text)
        self.assertIn("GRAFANA_PROMETHEUS_REMOTE_WRITE_USER", text)
        self.assertIn("GRAFANA_PROMETHEUS_REMOTE_WRITE_TOKEN", text)
        self.assertNotIn("GRAFANA_CLOUD_LOKI_API_KEY", text)
        self.assertNotIn("TEMPO_OTLP_PASSWORD", text)

    def test_production_deploy_workflow_pins_actions_to_full_commit_sha(self):
        text = WORKFLOW.read_text(encoding="utf-8")
        uses_refs = re.findall(r"uses:\s*([^\s#]+)", text)
        self.assertTrue(uses_refs)
        for ref in uses_refs:
            with self.subTest(ref=ref):
                self.assertRegex(ref, r"@[0-9a-f]{40}$")
                self.assertNotRegex(ref, r"@v\d+(?:\b|$)")

    def test_validate_only_skips_app_deploy_inputs_and_server_build_logic_for_migrations(self):
        workflow = WORKFLOW.read_text(encoding="utf-8")
        script = MIGRATION_SCRIPT.read_text(encoding="utf-8")
        self.assertIn("inputs.db_migration_mode != 'validate-only'", workflow)
        self.assertLess(
            workflow.index("db_migration_gate:"),
            workflow.index("deploy:"),
        )
        self.assertIn("SHAKA_MIGRATION_DIR: ${{ github.workspace }}/migration-sql/migration", workflow)
        self.assertNotIn("server-migration-source", workflow)
        self.assertNotIn("Set up Java 21 for Flyway Gradle tasks", workflow)
        self.assertNotIn("SHAKA_PROD_DB_PASSWORD: ${{ secrets.SHAKA_PROD_DB_PASSWORD }}\n      SHAKA_PROD_URL", workflow)
        self.assertNotIn("./gradlew", script)
        self.assertIn("never runs server Gradle/build logic with production secrets", script)

    def test_migration_gate_reuses_existing_production_secret_names(self):
        workflow = WORKFLOW.read_text(encoding="utf-8")
        script = MIGRATION_SCRIPT.read_text(encoding="utf-8")
        self.assertIn("SHAKA_PROD_DB_URL: ${{ secrets.SHAKA_PROD_DB_URL }}", workflow)
        self.assertIn("secrets.SHAKA_DB_USERNAME", workflow)
        self.assertIn("secrets.SHAKA_DB_PASSWORD", workflow)
        self.assertNotIn("secrets.SHAKA_PROD_DB_USERNAME", workflow)
        self.assertNotIn("secrets.SHAKA_PROD_DB_PASSWORD", workflow)
        self.assertNotIn("vars.SHAKA_FLYWAY_CLI_URL", workflow)
        self.assertNotIn("vars.SHAKA_MYSQL_CONNECTOR_J_URL", workflow)
        self.assertIn("defaults to pinned Flyway commandline 10.10.0", script)
        self.assertIn("defaults to pinned MySQL Connector/J 8.3.0", script)

    def test_migration_script_keeps_tool_pins_overridable(self):
        script = MIGRATION_SCRIPT.read_text(encoding="utf-8")
        self.assertIn('SHAKA_FLYWAY_CLI_URL="${SHAKA_FLYWAY_CLI_URL:-https://repo1.maven.org/', script)
        self.assertIn('SHAKA_FLYWAY_CLI_SHA256="${SHAKA_FLYWAY_CLI_SHA256:-77dd0af6', script)
        self.assertIn('SHAKA_MYSQL_CONNECTOR_J_URL="${SHAKA_MYSQL_CONNECTOR_J_URL:-https://repo1.maven.org/', script)
        self.assertIn('SHAKA_MYSQL_CONNECTOR_J_SHA256="${SHAKA_MYSQL_CONNECTOR_J_SHA256:-94e7fa', script)

    def test_database_migration_script_fails_closed_and_uses_ssh_tunnel(self):
        text = MIGRATION_SCRIPT.read_text(encoding="utf-8")
        self.assertIn("DB_MIGRATION_MODE must be one of: none, validate-only, apply", text)
        self.assertIn("pending Flyway migration detected", text)
        self.assertIn("DB_MIGRATION_CONFIRMATION=migrate-shaka-production", text)
        self.assertIn("flyway-commandline/10.10.0/flyway-commandline-10.10.0.tar.gz", text)
        self.assertIn("77dd0af6f85b7caba74126f98920d026ddc3b5682de590322582da7ee957c331", text)
        self.assertIn("mysql-connector-j/8.3.0/mysql-connector-j-8.3.0.jar", text)
        self.assertIn("94e7fa815370cdcefed915db7f53f88445fac110f8c3818392b992ec9ee6d295", text)
        self.assertIn("shasum -a 256 -c", text)
        self.assertIn("tar -xzf", text)
        self.assertIn("run_flyway_task info", text)
        self.assertIn("run_flyway_task validate", text)
        self.assertIn("run_flyway_task migrate", text)
        self.assertIn("-ignoreMigrationPatterns=*:pending", text)
        self.assertIn("grep -Eiq '\\|[[:space:]]*Pending[[:space:]]*\\|'", text)
        self.assertNotIn("(^|[[:space:]|])Pending", text)
        self.assertIn("SHAKA_FLYWAY_BASELINE_ON_MIGRATE must be true or false", text)
        self.assertIn("-baselineOnMigrate=true", text)
        self.assertIn("-baselineVersion=0", text)
        self.assertIn("StrictHostKeyChecking=yes", text)
        self.assertIn("ExitOnForwardFailure=yes", text)
        self.assertIn("-L \"127.0.0.1:${LOCAL_DB_PORT}:${DB_HOST}:${DB_PORT}\"", text)
        self.assertIn("socket.create_connection", text)
        self.assertNotIn("sleep 2", text)
        self.assertIn("SHAKA_PROD_DB_URL must not embed a password", text)
        self.assertIn("::add-mask::%s", text)
        self.assertIn("aws rds describe-db-instances", text)
        self.assertIn("BackupRetentionPeriod", text)
        self.assertIn("LatestRestorableTime", text)
        self.assertIn("isinstance(metadata, dict)", text)
        self.assertNotIn("echo \"$SHAKA_PROD_DB_PASSWORD", text)
        self.assertNotIn("-password=", text)
        self.assertNotIn("set -x", text)

    def test_deploy_script_preflights_agent_and_combined_alloy_credentials(self):
        text = SCRIPT.read_text(encoding="utf-8")
        self.assertIn("Preflighting production host and OpenTelemetry Java agent before app mutation", text)
        self.assertIn("opentelemetry-javaagent-${OTEL_JAVA_AGENT_VERSION}.jar", text)
        self.assertIn("StrictHostKeyChecking=yes", text)
        self.assertIn("UserKnownHostsFile", text)
        self.assertIn("OTEL_JAVA_AGENT_SHA256", text)
        self.assertIn("sha256sum -c -", text)
        self.assertIn("GRAFANA_CLOUD_OTLP_ENDPOINT", text)
        self.assertIn("GRAFANA_CLOUD_OTLP_USERNAME", text)
        self.assertIn("GRAFANA_CLOUD_OTLP_PASSWORD", text)
        self.assertIn("OTEL_METRICS_EXPORTER': 'otlp'", text)
        self.assertIn("OTEL_LOGS_EXPORTER': 'otlp'", text)
        self.assertIn("OTEL_TRACES_EXPORTER': 'otlp'", text)
        self.assertIn("sudo systemctl restart alloy", text)
        self.assertIn("rollback_remote", text)
        self.assertIn("rollback_from_backup", text)
        self.assertIn("/etc/nginx/conf.d/shaka-server.conf:shaka-server.conf", text)
        self.assertIn("/etc/alloy/config.alloy:config.alloy", text)
        self.assertIn("/etc/shaka/env:env", text)
        self.assertIn('"$(basename "$OBS_ENV_FILE")"', text)
        self.assertIn('OBS_ENV_BASE="$3"', text)
        self.assertIn("agent_option not in existing_java_tool_options", text)
        self.assertIn("ExecStartPre=", text)
        self.assertIn("missing required Alloy OTLP/remote_write env keys", text)
        self.assertIn("placeholder value is not allowed", text)
        self.assertIn("staged Alloy OTLP env file must not be group/world readable", text)
        self.assertIn("must be a Grafana Cloud HTTPS endpoint", text)
        self.assertIn("GRAFANA_CLOUD_OTLP_ENDPOINT", text)
        self.assertIn("sudo install -o root -g root -m 0600", text)
        self.assertIn("external health check failed", text)
        self.assertIn("must be a Grafana Cloud Prometheus remote_write endpoint", text)
        self.assertIn("GRAFANA_PROMETHEUS_REMOTE_WRITE_URL", text)
        self.assertIn("from urllib.parse import urlparse", text)
        self.assertIn("parsed.hostname", text)
        self.assertIn("parsed.path", text)
        self.assertNotIn('".grafana.net/api/prom/push" in remote_write_url', text)
        self.assertNotIn("https://*.grafana.net/api/prom/push", text)
        self.assertNotIn("GRAFANA_CLOUD_LOKI_API_KEY", text)
        self.assertNotIn("TEMPO_OTLP_PASSWORD", text)
        self.assertNotIn("journalctl -u alloy", text)

    def test_remote_write_url_validation_rejects_path_based_host_confusion(self):
        workflow = WORKFLOW.read_text(encoding="utf-8")
        script = SCRIPT.read_text(encoding="utf-8")
        for text in (workflow, script):
            self.assertIn("urlparse", text)
            self.assertRegex(text, r"parsed[.]hostname")
            self.assertRegex(text, r"parsed[.]path\s*!=\s*expected_path")
            self.assertIn("parsed.username or parsed.password", text)
            self.assertNotIn('".grafana.net/api/prom/push" in', text)
            self.assertNotIn("https://*.grafana.net/api/prom/push", text)

    def test_alloy_config_is_otlp_first_for_all_three_signals(self):
        text = ALLOY.read_text(encoding="utf-8")
        self.assertIn('otelcol.receiver.otlp "shaka"', text)
        self.assertIn('endpoint = "127.0.0.1:4317"', text)
        self.assertIn('endpoint = "127.0.0.1:4318"', text)
        self.assertIn('metrics = [otelcol.processor.transform.shaka.input]', text)
        self.assertIn('logs    = [otelcol.processor.transform.shaka.input]', text)
        self.assertIn('traces  = [otelcol.processor.transform.shaka.input]', text)
        self.assertIn('otelcol.exporter.otlphttp "grafana_cloud"', text)
        self.assertIn('endpoint = sys.env("GRAFANA_CLOUD_OTLP_ENDPOINT")', text)
        self.assertIn('username = sys.env("GRAFANA_CLOUD_OTLP_USERNAME")', text)
        self.assertIn('password = sys.env("GRAFANA_CLOUD_OTLP_PASSWORD")', text)
        self.assertIn('prometheus.exporter.unix "shaka_host"', text)
        self.assertIn('prometheus.remote_write "grafana_cloud"', text)
        self.assertIn('url = sys.env("GRAFANA_PROMETHEUS_REMOTE_WRITE_URL")', text)
        self.assertIn('password = sys.env("GRAFANA_PROMETHEUS_REMOTE_WRITE_TOKEN")', text)
        self.assertNotIn("loki.write", text)
        self.assertNotIn("processes {}", text)

    def test_runtime_config_lives_in_infra(self):
        self.assertTrue((ROOT / "deploy" / "nginx" / "shaka-server.conf").is_file())
        self.assertTrue(SYSTEMD.is_file())
        self.assertTrue((ROOT / "deploy" / "env" / "shaka-env.example").is_file())
        systemd_text = SYSTEMD.read_text(encoding="utf-8")
        self.assertIn("/opt/shaka/current.jar", systemd_text)
        self.assertIn("User=ubuntu", systemd_text)

    def test_nginx_no_longer_terminates_tls(self):
        nginx_text = (ROOT / "deploy" / "nginx" / "shaka-server.conf").read_text(encoding="utf-8")
        self.assertNotIn("ssl_certificate", nginx_text)
        self.assertNotIn("listen 443", nginx_text)
        self.assertNotIn("letsencrypt", nginx_text.lower())
        self.assertIn("listen 80;", nginx_text)
        self.assertIn("set_real_ip_from 172.31.0.0/16;", nginx_text)

    def test_nginx_keeps_actuator_lockdown(self):
        nginx_text = (ROOT / "deploy" / "nginx" / "shaka-server.conf").read_text(encoding="utf-8")
        self.assertIn("location = /actuator/prometheus { deny all; return 403; }", nginx_text)
        self.assertIn("location /actuator/ { deny all; return 403; }", nginx_text)

if __name__ == "__main__":
    unittest.main()
